boards/UNTESTED_talos-2 : explicitely disable kbd and inclusion of keyboard mappings for this board
TODO: Would need patching

Error:
user@localhost:~/heads$ cat /home/user/heads/build/ppc64/log/kbd.log
make -C "/home/user/heads/build/ppc64/kbd-2.6.1" -j12 --load-average=18  CC=/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-gcc -fdebug-prefix-map=/home/user/heads=heads -gno-record-gcc-switches -D__MUSL__ --sysroot /home/user/heads/install/ppc64 -isystem /home/user/heads/install/ppc64/include -L/home/user/heads/install/ppc64/lib  AR=/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-ar LD=/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-ld STRIP=/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-strip NM=/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-nm OBJCOPY=/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-objcopy OBJDUMP=/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-objdump PKG_CONFIG_PATH= PKG_CONFIG_LIBDIR=/home/user/heads/install/ppc64/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR=/home/user/heads/install/ppc64
make[1]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1'
make  all-recursive
make[2]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1'
Making all in src
make[3]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src'
Making all in libcommon
make[4]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libcommon'
  CC       getfd.o
  CC       error.o
  CC       version.o
  AR       libcommon.a
/home/user/heads/crossgcc/ppc64/bin/powerpc64le-linux-musl-ar: `u' modifier ignored since `D' is the default (see `U')
make[4]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libcommon'
Making all in libkbdfile
make[4]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkbdfile'
  CC       init.lo
  CC       kbdfile.lo
  CCLD     libkbdfile.la
make[4]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkbdfile'
Making all in libkfont
make[4]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkfont'
  CC       psffontop.lo
  CC       psfxtable.lo
  CC       utf8.lo
  CC       kdmapop.lo
  CC       context.lo
  CC       unicode.lo
  CC       kdfontop.lo
  CC       loadunimap.lo
  CC       mapscrn.lo
  CC       setfont.lo
setfont.c: In function 'try_loadfont':
setfont.c:102:14: warning: conversion from 'int' to 'unsigned char' may change value [-Wconversion]
  102 |        b2 |= 3 << (j * 2);
      |              ^
mapscrn.c: In function 'kfont_load_consolemap':
mapscrn.c:161:13: warning: conversion from 'int' to 'short unsigned int' may change value [-Wconversion]
  161 |   ubuf[i] = (0xf000 + i);
      |             ^
loadunimap.c: In function 'parseline':
loadunimap.c:220:24: warning: conversion from 'int' to 'short unsigned int' may change value [-Wconversion]
  220 |    unsigned short un = un0 - fp0;
      |                        ^~~
loadunimap.c:221:38: warning: conversion from 'int' to 'short unsigned int' may change value [-Wconversion]
  221 |    if ((ret = add_unipair(ctx, i, un + i, list, listsz, listct)) < 0)
      |                                   ~~~^~~
  CCLD     libkfont.la
make[4]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkfont'
Making all in libkeymap
make[4]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkeymap'
make  all-am
make[5]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkeymap'
  CC       array.lo
  CC       common.lo
  CC       dump.lo
  CC       kernel.lo
  CC       kmap.lo
  CC       func.lo
  CC       diacr.lo
  CC       loadkeys.lo
  CC       summary.lo
  CC       parser.lo
  CC       modifiers.lo
  CC       analyze.lo
kernel.c: In function 'lk_kernel_diacrs':
kernel.c:101:16: warning: conversion from 'long unsigned int' to 'int' may change value [-Wconversion]
  101 |  if (ioctl(fd, request, (unsigned long)&kd)) {
      |                ^~~~~~~
  CC       ksyms.lo
  CCLD     libkeymap.la
make[5]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkeymap'
make[4]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/libkeymap'
Making all in vlock
make[4]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/vlock'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src/vlock'
make[4]: Entering directory '/home/user/heads/build/ppc64/kbd-2.6.1/src'
  CC       mapscrn.o
  CC       loadunimap.o
  CC       dumpkeys.o
  CC       showkey.o
  CC       loadkeys.o
  CC       setfont.o
  CC       showconsolefont.o
  CC       setmetamode.o
  CC       setleds.o
  CC       kbd_mode.o
  CC       psfxtable.o
  CC       fgconsole.o
  CC       kbdrate.o
  CC       chvt.o
  CC       deallocvt.o
  CC       openvt.o
  CC       kbdinfo.o
  CC       getkeycodes.o
  CC       setvtrgb.o
  CC       setkeycodes.o
  CC       resizecons.o
  CCLD     mapscrn
  CCLD     loadunimap
resizecons.c: In function 'main':
resizecons.c:303:19: warning: signed conversion from 'long unsigned int' to 'int' changes value from '2148037735' to '-2146929561' [-Wsign-conversion]
  303 |     if (ioctl(fd, TIOCSWINSZ, &winsize))
      |                   ^~~~~~~~~~
  CCLD     dumpkeys
  CCLD     loadkeys
resizecons.c: In function 'vga_set_cursor':
resizecons.c:394:2: error: inconsistent operand constraints in an 'asm'
  394 |  __asm__ volatile("outb %0,%1"
      |  ^~~~~~~
resizecons.c:402:2: error: inconsistent operand constraints in an 'asm'
  402 |  __asm__ volatile("inb %1,%0"
      |  ^~~~~~~
resizecons.c:394:2: error: inconsistent operand constraints in an 'asm'
  394 |  __asm__ volatile("outb %0,%1"
      |  ^~~~~~~
resizecons.c:394:2: error: inconsistent operand constraints in an 'asm'
  394 |  __asm__ volatile("outb %0,%1"
      |  ^~~~~~~
resizecons.c:402:2: error: inconsistent operand constraints in an 'asm'
  402 |  __asm__ volatile("inb %1,%0"
      |  ^~~~~~~
resizecons.c:394:2: error: inconsistent operand constraints in an 'asm'
  394 |  __asm__ volatile("outb %0,%1"
      |  ^~~~~~~
  CCLD     showkey
make[4]: *** [Makefile:993: resizecons.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src'
make[3]: *** [Makefile:1040: all-recursive] Error 1
make[3]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1/src'
make[2]: *** [Makefile:489: all-recursive] Error 1
make[2]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1'
make[1]: *** [Makefile:420: all] Error 2
make[1]: Leaving directory '/home/user/heads/build/ppc64/kbd-2.6.1'

Signed-off-by: Thierry Laurion <insurgo@riseup.net>